server:
  port: 8089

spring:
  application:
    name: lab
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lab?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
    elasticsearch:
      repositories:
        enabled: true
      uris: http://localhost:9200
  rocketmq:
    name-server: localhost:9876
    producer:
      group: lab-producer-group
      send-message-timeout: 3000
    consumer:
      group: lab-consumer-group
  autoconfigure:
    import: org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration
  # File upload configuration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cqu.lab.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 设置默认枚举处理器
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      # 表名前缀
      table-prefix: ""
      # 大写命名
      capital-mode: false

redisson:
  single-server-config:
    address: redis://localhost:6379
    password: 123456
    database: 0


elasticsearch:
  host: localhost
  port: 9200
  username:
  password:
  user-index: lab_users
  enabled: false

# Aliyun OSS Configuration
  aliyun:
    oss:
      endpoint: https://oss-cn-chengdu.aliyuncs.com
      accessKeyId: your-access-key-id
      accessKeySecret: your-access-key-secret
      bucketName: cqulab
      urlPrefix: https://cqulab.oss-cn-chengdu.aliyuncs.com/

